-- Set Valentine Event NPC for level 60
update creature_template set creature_template.minlevel = 60, creature_template.maxlevel = 60 where name = 'Crazed Apothecary';
update creature_template set creature_template.minlevel = 62, creature_template.maxlevel = 62, creature_template.HealthModifier = 7, creature_template.DamageModifier = 2 where entry = 36272 OR entry = 36296 OR entry = 36565;
-- Create new Valentine item: Fumigator's Mask
DELETE FROM item_template_locale WHERE id = 60000;
DELETE FROM item_template WHERE entry = 60000;
INSERT INTO item_template (`entry`,
    `class`,
    `subclass`,
    `SoundOverrideSubclass`,
    `name`,
    `displayid`,
    `Quality`,
    `Flags`,
    `FlagsExtra`,
    `BuyCount`,
    `BuyPrice`,
    `SellPrice`,
    `InventoryType`,
    `AllowableClass`,
    `AllowableRace`,
    `ItemLevel`,
    `RequiredLevel`,
    `RequiredSkill`,
    `RequiredSkillRank`,
    `requiredspell`,
    `requiredhonorrank`,
    `RequiredCityRank`,
    `RequiredReputationFaction`,
    `RequiredReputationRank`,
    `maxcount`,
    `stackable`,
    `ContainerSlots`,
    `StatsCount`,
    `stat_type1`,
    `stat_value1`,
    `stat_type2`,
    `stat_value2`,
    `stat_type3`,
    `stat_value3`,
    `stat_type4`,
    `stat_value4`,
    `stat_type5`,
    `stat_value5`,
    `stat_type6`,
    `stat_value6`,
    `stat_type7`,
    `stat_value7`,
    `stat_type8`,
    `stat_value8`,
    `stat_type9`,
    `stat_value9`,
    `stat_type10`,
    `stat_value10`,
    `ScalingStatDistribution`,
    `ScalingStatValue`,
    `dmg_min1`,
    `dmg_max1`,
    `dmg_type1`,
    `dmg_min2`,
    `dmg_max2`,
    `dmg_type2`,
    `armor`,
    `holy_res`,
    `fire_res`,
    `nature_res`,
    `frost_res`,
    `shadow_res`,
    `arcane_res`,
    `delay`,
    `ammo_type`,
    `RangedModRange`,
    `spellid_1`,
    `spelltrigger_1`,
    `spellcharges_1`,
    `spellppmRate_1`,
    `spellcooldown_1`,
    `spellcategory_1`,
    `spellcategorycooldown_1`,
    `spellid_2`,
    `spelltrigger_2`,
    `spellcharges_2`,
    `spellppmRate_2`,
    `spellcooldown_2`,
    `spellcategory_2`,
    `spellcategorycooldown_2`,
    `spellid_3`,
    `spelltrigger_3`,
    `spellcharges_3`,
    `spellppmRate_3`,
    `spellcooldown_3`,
    `spellcategory_3`,
    `spellcategorycooldown_3`,
    `spellid_4`,
    `spelltrigger_4`,
    `spellcharges_4`,
    `spellppmRate_4`,
    `spellcooldown_4`,
    `spellcategory_4`,
    `spellcategorycooldown_4`,
    `spellid_5`,
    `spelltrigger_5`,
    `spellcharges_5`,
    `spellppmRate_5`,
    `spellcooldown_5`,
    `spellcategory_5`,
    `spellcategorycooldown_5`,
    `bonding`,
    `description`,
    `PageText`,
    `LanguageID`,
    `PageMaterial`,
    `startquest`,
    `lockid`,
    `Material`,
    `sheath`,
    `RandomProperty`,
    `RandomSuffix`,
    `block`,
    `itemset`,
    `MaxDurability`,
    `area`,
    `Map`,
    `BagFamily`,
    `TotemCategory`,
    `socketColor_1`,
    `socketContent_1`,
    `socketColor_2`,
    `socketContent_2`,
    `socketColor_3`,
    `socketContent_3`,
    `socketBonus`,
    `GemProperties`,
    `RequiredDisenchantSkill`,
    `ArmorDamageModifier`,
    `duration`,
    `ItemLimitCategory`,
    `HolidayId`,
    `ScriptName`,
    `DisenchantID`,
    `FoodType`,
    `minMoneyLoot`,
    `maxMoneyLoot`,
    `flagsCustom`,
    `VerifiedBuild`)
SELECT 60000,
    `class`,
    `subclass`,
    `SoundOverrideSubclass`,
    "Fumigator's Mask",
    `displayid`,
    `Quality`,
    `Flags`,
    `FlagsExtra`,
    `BuyCount`,
    87325,
    17498,
    `InventoryType`,
    `AllowableClass`,
    `AllowableRace`,
    70,
    55,
    `RequiredSkill`,
    `RequiredSkillRank`,
    `requiredspell`,
    `requiredhonorrank`,
    `RequiredCityRank`,
    `RequiredReputationFaction`,
    `RequiredReputationRank`,
    `maxcount`,
    `stackable`,
    `ContainerSlots`,
    `StatsCount`,
    `stat_type1`,
    `stat_value1`,
    `stat_type2`,
    `stat_value2`,
    `stat_type3`,
    `stat_value3`,
    `stat_type4`,
    `stat_value4`,
    `stat_type5`,
    `stat_value5`,
    `stat_type6`,
    `stat_value6`,
    `stat_type7`,
    `stat_value7`,
    `stat_type8`,
    `stat_value8`,
    `stat_type9`,
    `stat_value9`,
    `stat_type10`,
    `stat_value10`,
    `ScalingStatDistribution`,
    `ScalingStatValue`,
    `dmg_min1`,
    `dmg_max1`,
    `dmg_type1`,
    `dmg_min2`,
    `dmg_max2`,
    `dmg_type2`,
	80,
    `holy_res`,
    `fire_res`,
    30,
    `frost_res`,
    `shadow_res`,
    `arcane_res`,
    `delay`,
    `ammo_type`,
    `RangedModRange`,
    `spellid_1`,
    `spelltrigger_1`,
    `spellcharges_1`,
    `spellppmRate_1`,
    `spellcooldown_1`,
    `spellcategory_1`,
    `spellcategorycooldown_1`,
    37615,
    `spelltrigger_2`,
    `spellcharges_2`,
    `spellppmRate_2`,
    `spellcooldown_2`,
    `spellcategory_2`,
    300000,
    `spellid_3`,
    `spelltrigger_3`,
    `spellcharges_3`,
    `spellppmRate_3`,
    `spellcooldown_3`,
    `spellcategory_3`,
    `spellcategorycooldown_3`,
    `spellid_4`,
    `spelltrigger_4`,
    `spellcharges_4`,
    `spellppmRate_4`,
    `spellcooldown_4`,
    `spellcategory_4`,
    `spellcategorycooldown_4`,
    `spellid_5`,
    `spelltrigger_5`,
    `spellcharges_5`,
    `spellppmRate_5`,
    `spellcooldown_5`,
    `spellcategory_5`,
    `spellcategorycooldown_5`,
    `bonding`,
    `description`,
    `PageText`,
    `LanguageID`,
    `PageMaterial`,
    `startquest`,
    `lockid`,
    `Material`,
    `sheath`,
    `RandomProperty`,
    `RandomSuffix`,
    `block`,
    `itemset`,
    `MaxDurability`,
    `area`,
    `Map`,
    `BagFamily`,
    `TotemCategory`,
    `socketColor_1`,
    `socketContent_1`,
    `socketColor_2`,
    `socketContent_2`,
    `socketColor_3`,
    `socketContent_3`,
    `socketBonus`,
    `GemProperties`,
    225,
    `ArmorDamageModifier`,
    `duration`,
    `ItemLimitCategory`,
    `HolidayId`,
    `ScriptName`,
    49,
    `FoodType`,
    `minMoneyLoot`,
    `maxMoneyLoot`,
    `flagsCustom`,
    `VerifiedBuild`
FROM `world`.`item_template` WHERE name = "Vile Fumigator's Mask";

INSERT INTO item_template_locale (`ID`,
`locale`,
`Name`,
`Description`,
`VerifiedBuild`)
SELECT 60000,
    `locale`,
    "Masque de fumigateur",
    `Description`,
    `VerifiedBuild`
FROM `world`.`item_template_locale` WHERE ID = 50741 AND locale = 'frFR';

INSERT INTO item_template_locale (`ID`,
`locale`,
`Name`,
`Description`,
`VerifiedBuild`)
SELECT 60000,
    `locale`,
    "Máscara de fumigador",
    `Description`,
    `VerifiedBuild`
FROM `world`.`item_template_locale` WHERE ID = 50741 AND locale = 'esES';

INSERT INTO item_template_locale (`ID`,
`locale`,
`Name`,
`Description`,
`VerifiedBuild`)
SELECT 60000,
    `locale`,
    "Máscara de fumigador",
    `Description`,
    `VerifiedBuild`
FROM `world`.`item_template_locale` WHERE ID = 50741 AND locale = 'esMX';
INSERT INTO item_template_locale (`ID`,
`locale`,
`Name`,
`Description`,
`VerifiedBuild`)
SELECT 60000,
    `locale`,
    "Maske des Ausräucherers",
    `Description`,
    `VerifiedBuild`
FROM `world`.`item_template_locale` WHERE ID = 50741 AND locale = 'deDE';
INSERT INTO item_template_locale (`ID`,
`locale`,
`Name`,
`Description`,
`VerifiedBuild`)
SELECT 60000,
    `locale`,
    "훈증기의 가면",
    `Description`,
    `VerifiedBuild`
FROM `world`.`item_template_locale` WHERE ID = 50741 AND locale = 'koKR';
INSERT INTO item_template_locale (`ID`,
`locale`,
`Name`,
`Description`,
`VerifiedBuild`)
SELECT 60000,
    `locale`,
    "Маска фумигатора",
    `Description`,
    `VerifiedBuild`
FROM `world`.`item_template_locale` WHERE ID = 50741 AND locale = 'ruRU';
INSERT INTO item_template_locale (`ID`,
`locale`,
`Name`,
`Description`,
`VerifiedBuild`)
SELECT 60000,
    `locale`,
    "熏蒸器口罩",
    `Description`,
    `VerifiedBuild`
FROM `world`.`item_template_locale` WHERE ID = 50741 AND locale = 'zhCN';
INSERT INTO item_template_locale (`ID`,
`locale`,
`Name`,
`Description`,
`VerifiedBuild`)
SELECT 60000,
    `locale`,
    "薰蒸面罩",
    `Description`,
    `VerifiedBuild`
FROM `world`.`item_template_locale` WHERE ID = 50741 AND locale = 'zhTW';

-- Reset Valentine loot table for Hummel 60
UPDATE creature_loot_template SET Chance = 50 WHERE reference = 50011;
UPDATE creature_loot_template SET Chance = 100 WHERE item = 50320;
UPDATE creature_loot_template SET Chance = 100 WHERE item = 49641;
UPDATE creature_loot_template SET Reference = 0, Item = 51995 WHERE Reference = 50010 AND Item = 1;
UPDATE reference_loot_template SET Item = 60000 WHERE Item = 50741;
-- Set Valentine Event Quests for level 60
UPDATE quest_template SET quest_template.QuestLevel = 60, quest_template.MinLevel = 55 WHERE LogTitle = "Something is in the Air (and it Ain't Love)";
UPDATE quest_template SET quest_template.QuestLevel = 60, quest_template.MinLevel = 55 WHERE LogTitle = "You've Been Served";
